dir: ./tasks
web:
  auto_open_browser: false
sync:
  sources:
    - name: github
      project: driangle/taskmd
      token_env: GITHUB_TOKEN_TASKMD
      output_dir: tasks/github
      field_map:
        labels_to_tags: true
        assignee_to_owner: true
scopes:
  cli:
    paths:
      - "apps/cli/"
  cli/report:
    paths:
      - "apps/cli/internal/cli/report.go"
  cli/metrics:
    paths:
      - "apps/cli/internal/metrics/"
      - "apps/cli/internal/cli/metrics.go"
  cli/graph:
    paths:
      - "apps/cli/internal/graph/"
      - "apps/cli/internal/cli/graph.go"
  cli/mcp:
    paths:
      - "apps/cli/internal/mcp/"
      - "apps/cli/internal/cli/mcp.go"
  cli/validate:
    paths:
      - "apps/cli/internal/validate/"
      - "apps/cli/internal/cli/validate.go"
  cli/config:
    paths:
      - "apps/cli/"
  sync/core:
    paths:
      - "apps/cli/internal/sync/source.go"
      - "apps/cli/internal/sync/engine.go"
      - "apps/cli/internal/sync/registry.go"
      - "apps/cli/internal/sync/mapper.go"
      - "apps/cli/internal/sync/config.go"
  sync/jira:
    paths:
      - "apps/cli/internal/sync/jira/"
  sync/linear:
    paths:
      - "apps/cli/internal/sync/linear/"
  sync/trello:
    paths:
      - "apps/cli/internal/sync/trello/"
  vscode:
    paths:
      - "apps/vscode/"
  web:
    paths:
      - "apps/web/"
  web/layout:
    paths:
      - "apps/web/src/components/layout/"
  web/board:
    paths:
      - "apps/web/src/components/board/"
  web/graph:
    paths:
      - "apps/web/src/components/graph/"
  web/tasks:
    paths:
      - "apps/web/src/components/tasks/"
  web/stats:
    paths:
      - "apps/web/src/components/stats/"
